=== L-Sun/HitagiEngine/assets/utils/material_schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "default": {},
    "Material define": "Root Schema",
    "required": [
        "name",
        "vertex_shader",
        "pixel_shader",
        "primitive"
    ],
    "properties": {
        "name": {
            "type": "string",
            "default": "",
            "title": "The name of material"
        },
        "vertex_shader": {
            "type": "string",
            "default": "",
            "title": "vertex shader path",
            "examples": [
                "assets/shaders/phong.hlsl"
            ],
            "description": "The HLSL vertex shader path with entry `VSMain`"
        },
        "pixel_shader": {
            "type": "string",
            "default": "",
            "title": "pixel shader path",
            "examples": [
                "assets/shaders/phong.hlsl"
            ],
            "description": "The HLSL pixel shader path with entry `PSMain`"
        },
        "primitive": {
            "type": "string",
            "default": "TriangleList",
            "title": "Primitive type",
            "examples": [
                "TriangleList"
            ],
            "enum": [
                "PointList",
                "LineList",
                "LineStrip",
                "TriangleList",
                "TriangleStrip",
                "LineListAdjacency",
                "LineStripAdjacency",
                "TriangleListAdjacency",
                "TriangleStripAdjacency"
            ]
        },
        "parameters": {
            "type": "array",
            "default": [],
            "title": "The parameters of material.",
            "items": {
                "type": "object",
                "title": "Material parameter",
                "required": [
                    "name",
                    "type"
                ],
                "properties": {
                    "name": {
                        "type": "string",
                        "title": "The name of parameter",
                        "examples": [
                            "ambient",
                            "diffuse",
                            "emission",
                            "specular_power",
                            "ambient_texture",
                            "diffuse_texture"
                        ]
                    },
                    "type": {
                        "type": "string",
                        "title": "The type of parameter",
                        "examples": [
                            "vec4f",
                            "vec2f",
                            "vec3f",
                            "float",
                            "texture"
                        ],
                        "enum": [
                            "float",
                            "int32",
                            "uint32",
                            "vec2i",
                            "vec2u",
                            "vec2f",
                            "vec3i",
                            "vec3u",
                            "vec3f",
                            "vec4i",
                            "vec4u",
                            "mat4f",
                            "vec4f",
                            "texture"
                        ]
                    },
                    "default": {
                        "type": [
                            "array",
                            "number"
                        ],
                        "title": "The default Schema",
                        "items": {
                            "type": "number",
                            "title": "A Schema",
                            "examples": [
                                0.1,
                                0.2,
                                0.3,
                                0.4
                            ]
                        }
                    }
                },
                "examples": [
                    {
                        "name": "ambient",
                        "type": "vec4f",
                        "default": [
                            0.1,
                            0.2,
                            0.3,
                            0.4
                        ]
                    }
                ]
            },
            "description": "The parameters of material, which must be matched with the material constant buffer in shader."
        }
    },
    "examples": [
        {
            "name": "Phong",
            "vertex_shader": "assets/shaders/phong.hlsl",
            "pixel_shader": "assets/shaders/phong.hlsl",
            "primitive": "TriangleList",
            "parameters": [
                {
                    "name": "ambient",
                    "type": "vec4f",
                    "default": [
                        0.1,
                        0.2,
                        0.3,
                        0.4
                    ]
                },
                {
                    "name": "diffuse",
                    "type": "vec2f"
                },
                {
                    "name": "emission",
                    "type": "vec3f",
                    "default": [
                        0.1,
                        0.2,
                        0.3
                    ]
                },
                {
                    "name": "specular_power",
                    "type": "float",
                    "default": 1.0
                },
                {
                    "name": "ambient_texture",
                    "type": "texture"
                },
                {
                    "name": "diffuse_texture",
                    "type": "texture"
                }
            ]
        }
    ]
}

=== L-Sun/HitagiEngine/assets/materials/phong.json
{
    "$schema": "../utils/material_schema.json",
    "name": "Phong",
    "vertex_shader": "assets/shaders/phong.hlsl",
    "pixel_shader": "assets/shaders/phong.hlsl",
    "primitive": "TriangleList",
    "parameters": [
        {
            "name": "diffuse",
            "type": "vec3f"
        },
        {
            "name": "diffuse_texture",
            "type": "texture"
        },
        {
            "name": "specular",
            "type": "vec3f"
        },
        {
            "name": "specular_texture",
            "type": "texture"
        },
        {
            "name": "ambient",
            "type": "vec3f"
        },
        {
            "name": "ambient_texture",
            "type": "texture"
        },
        {
            "name": "emissive",
            "type": "vec3f"
        },
        {
            "name": "emissive_texture",
            "type": "texture"
        },
        {
            "name": "shininess",
            "type": "float"
        }
    ]
}
